version: 2
jobs:
  build:
    working_directory: ~/gradle-build
    docker:
      - image: egis/build-slave
    steps:
      - checkout
      - run: chmod +x gradlew
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run: ./gradlew jar
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: build/libs
      - deploy:
          command: |
            ./gradlew publishPlugins